{% set name = "SWV_AnyPeakFinder" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: "https://github.com/Paradoxdruid/SWVAnyPeakFinder.git"
  git_rev: "v1.9.0"

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy 
    - scipy 
    - matplotlib 
    - lmfit

test:
  imports:
    - SWV_AnyPeakFinder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Paradoxdruid/SWVAnyPeakFinder
  summary: GUI application for resolving peak heights in square-wave voltammetry datafiles.
  license: GPL-v3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Paradoxdruid
